### ISSUE TITLE
This is not compatible with videojs version 5.0

### ISSUE THREAD

**Issue by pujoey** [Mewte/videojs-logobrand#9]
As per 5.0 Change Details, to make it work for v5 videojs.util.mergeOptions needs to be videojs.mergeOptions.  Took me forever to figure it out why it won't work.

videojs.util.mergeOptions   -->   videojs.mergeOptions
https://github.com/videojs/video.js/wiki/5.0-Change-Details

**Comment by vhmth** [comment]
Just a heads up that this is still the case. I've forked this repo into our org to get around it for now.
